# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ff0c6a7188ac3fd035ad3825a6f018ed5cd73686a801157f973044163920b67b4f86dfe81942b8e86b162311943b75a3fd90f7054f684edeccf700c94a4c77f

test:
  secret_key_base: 764272c6a68d13d0b4432827ac02ca5119913a54b8a364d15842cb44eaac37444d5b7a30855a40f395efb6e3b4b38611556b65ed5fea1bfdeeae75a3ef76dcc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
